---
- name: "install_undercloud | Set hostname "
  shell: "hostnamectl set-hostname {{ fqdn }}"
  become: True

- name: "install_undercloud | set hostname --transient "
  shell: "hostnamectl --transient set-hostname {{ fqdn }}"
  become: True

- name: "install_undercloud |  Register rhel"
  shell: "subscription-manager register --force --org={{ myorg }} --activationkey={{ mykey }}"
  become: True
  ignore_errors: yes

- name: "Enable epel if needed"
  command:  yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
  become: True


